# GOAL
# Sent by the Client (UI) to start a game
int32 duration_sec    # Game duration in seconds
string mode   # strategy mode (e.g., "manual", "auto_basic", "auto_smart")
string player_name    

---
# RESULT
# Sent by the Server (Manager) when the game ends
int32 final_score
bool success          # True if the game finished normally, False if aborted
---
# FEEDBACK
# Sent periodically by the Server during the game to update the interface
float32 remaining_time_sec
float32 current_energy
int32 current_score